let lessons = [
    {
        id: 1,
        lesson: "English",
        location: "Brighton",
        price: 25,
        image:'src/images/english.jpg',
        spaces: 5,
        availableInventory : 5,
    },
    {
        id: 2,
        lesson: "Maths",
        location: "Madrid",
        price: 35,
        image: "src/images/math.jpg",
        spaces: 3,
        availableInventory : 3,
    },
    {
        id: 3,
        lesson: "Biology",
        location: "Birmingham",
        price: 25,
        image: "src/images/bio.jpg",
        spaces: 7,
        availableInventory : 7,
    },
    {
        id: 4,
        lesson: "Comp Sci",
        location: "Wales",
        price: 40,
        image: "src/images/comp.jpg",
        spaces: 1,
        availableInventory : 1,
    },
    {
        id: 5,
        lesson: "Arts/Design",
        location: "Paddington",
        price: 60,
        image: "src/images/art.jpg",
        spaces: 1,
        availableInventory : 1,
    },
    {
        id: 6,
        lesson: "Food",
        location: "Ilsington",
        price: 20,
        image: "src/images/food.jpg",
        spaces: 8,
        availableInventory : 8,
    },
    {
        id: 7,
        lesson: "Music",
        location: "Camden",
        price: 30,
        image: "src/images/music.jpg",
        spaces: 0,
        availableInventory : 0,
    },
    {
        id: 8,
        lesson: "Business",
        location: "Manchester",
        price: 35,
        image: "src/images/business.jpg",
        spaces: 2,
        availableInventory : 2,
    },
    {
        id: 9,
        lesson: "Dance",
        location: "Camden",
        price: 35,
        image: "src/images/dance.jpg",
        spaces: 0,
        availableInventory : 0,
    },
    {
        id: 10,
        lesson: "Photography",
        location: "South London",
        price: 80,
        image: "src/images/photo.jpg",
        spaces: 4,
        availableInventory : 4,
    },


]
